POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vc2NoaW5vIiwiaWQiOiI2OTYzMjFmNjJlODlhZjM5OTQxYjQ4YmMiLCJpYXQiOjE3NjgxNzQxNDV9.KB3r7dUTyMcKu0S9qxljm01w04wfiCrCm-ScEcUDiso

{
"content": "VSCODE", "important": false
}
